def foo(param):
    match param:
        case {1: ""} | {2: ""} | x | {3: ""}:  # <- unreachable
            ...
        case _ | 2:  # <- unreachable
            ...
        case {1: ""} | dict() | {2: ""}:  # <- unreachable
            ...
